name: Oracle
main: name.richardson.james.oracle.Oracle
author: James Richardson (grandwazir)
website: https://github.com/grandwazir/Oracle 
description: Matches questions to regular expressions to provide in game help.
version: 1.0.0

commands:
  help:
    description: Ask a question to the oracle
    usage: /help [question]
    